import Header from './Header'
import Navbar from './Navbar'
import Sidebar from './Sidebar'
import SectionIntro from './SectionIntro'
import SectionValor from './SectionValor'
import SectionPrincipios from './SectionPrincipios'
import Servicios from './Servicios'
import Footer from './Footer'
import Contact from './Contact'
export { Header, Navbar, Sidebar, SectionIntro, SectionValor, SectionPrincipios, Servicios, Footer, Contact }